### ISSUE TITLE
From action sequences to DAGs

### ISSUE THREAD

**Issue by sebinside** [DataFlowAnalysis/DataFlowAnalysis#100]
This issue serves as a placeholder for the starting work on moving the analysis model from sequences to directed acyclic graphs initially mentioned in #86. To be continued...

**Comment by sebinside** [comment]
@Entenwilli @01Parzival10 I discussed this again with Nicolas because I thought that our ideas from the last meeting missed one important part: The individual flow graphs are, in fact, not individual, but parts of a complete flow graph, that holds more information than just a list of subgraphs. To be mathematically precise: Each graph is an induced subgraph `G[x]`, induced by the sink `x`. Although they are not connected, they still belong to the same DAG. So here is the updated proposal:  

Let's define `FlowGraph`, `PartialFlowGraph`, and `Vertex`. 

**Flow graphs** hold a list of partial graphs and also provide methods for, e.g., extracting the graph from DFDs or PCM (can be using something like an `ActionSequenceFinder` internally), or for lookup of vertices that represent the same model elements (PCM elements or DFD nodes). 

Each **partial flow graph** represents the induced subgraph of one sink. Thus, it should contain methods for the propagation, for the lookup of elements that meet a constraint, and for getting the sink (and in the case of PCM even getting the source, because partial flow graphs are always a sequence in PCM).

A **vertex** represents one DFD node or one relevant PCM element, holds node and data characteristics, and knows about its preceding vertices. The vertex knows how to get node characteristics (could, again, be using a calculator) and how to process ingoing data characteristics (i.e., the node's behavior). However, only the partial flow graph knows how to propagate, so the partial flow assigns data characteristics to vertices.

Of course, this also means we have abstract flow graphs, partial flow graphs and vertices, and also specific implementations for DFD and PCM. This not only enhances the capabilities of the analysis (e.g., joined flows) but makes the analysis also way easier to understand and unifies a lot of concepts. Furthermore, we would also not break the object-oriented paradigm that often :)

**Comment by Entenwilli** [comment]
In rebuilding the DataFlowAnalysis on Flow Graphs for PCM, I have encountered an issue that I would like to discuss:

Currently, when a SEFF is called, the data flow variables that are passed onto the next element are filtered for the parameters of the SEFF. When returning, only the RETURN Variable is passed back to the calling SEFF. Furthermore, the characteristics that were applied when calling are also applied when returning from the Call.

This leads to an issue:
When evaluating a return from an SEFF there are two previous nodes that data flow variables originate from: The Calling Vertex and the Returning Vertex from the Callee. This should lead to two previous Vertices that are saved in the Partial Flow Graph.

Now to the larger concern of mine:
When looking into Stephan's Dissertation, I found two concerning things: First, the Representation of Calls does not discuss how this case should be handled (correct me, if there is one!). So far, Ii've read through chapter 7.2
Second, looking at Figure 7,11 on page 176, there seems to be converging flows, even in PCM! How do we handle that case?

Overall, I think it's time to discuss semantics again next Tuesday, @sebinside @Nicolas-Boltz

**Comment by sebinside** [comment]
Just a quick thought: "the characteristics that were applied when calling are also applied when returning from the Call" - why? this seems to be counterintuitive as the resulting characteristics should only depend on the characteristics of the RETURN variable, or am I wrong? 

Regarding figure 7.11, I think the representation of the data flow in the thesis is different to our representation of flow graphs. The SEFF in 7.11 ist a synchronous call resulting in a linear sequence of actions. Thus, I would guess we can ignore this as it does not cause joined streams, at least at first glimpse. PartialFlowGraphs (or even our Flow Graphs) are not data flow diagrams like drawn by Stephan but represent them from a processing point of view. Thus, the representation of our initial data structure and the representation as data flow diagram may differ.

**Comment by sebinside** [comment]
This looks problematic. SEFFs with multiple input parameters are totally valid, and defining an external call with a subset of these parameters is also valid. Thus, we have to deal with this kinda scoping problem. However, I don't have an easy solution at hand, I can just say, that we can not ignore it, unfortunately.

I mean, an "easy" solution would be to break the assumption that PFGs are linear sequences in PCM and represent such behavior as joined stream, replicating something like figure 7.11. However, I don't know about the consequences of such a decision.
