### ISSUE TITLE
Implement converters from and to the DFD meta model

### ISSUE THREAD

**Issue by Nicolas-Boltz** [DataFlowAnalysis/DataFlowAnalysis#117]
Using the json or PlantUML DFD representations provided in the dataset [https://github.com/tuhh-softsec/microSecEnD](https://github.com/tuhh-softsec/microSecEnD) as input.
The output should be a model instance of the DFD Metamodel.

It would be best to create a new repository for the transformation code and resulting DFD model instances.

**Comment by sebinside** [comment]
To be more precise, we need a bundle `org.dataflowanalysis.analysis.converter` in the core repository that provides the following functionality, e.g., in separate packages:
1. microSecEnD to DFD
2. DFD to Web Viewer JSON
3. Web Viewer JSON to DFD
4. *Optional*, depending on the existing [converter](https://tuhh-softsec.github.io/microSecEnD/conversion.html): microSecEnD PUML to DFD
5. ASs to DFD, depending on the progress of #100 probably PFG to DFD
