### ISSUE TITLE
Implement formatting guidelines

### ISSUE THREAD

**Issue by sebinside** [DataFlowAnalysis/DataFlowAnalysis#125]
Currently, we use a mix of Eclipse default and arbitrary custom formatting guidelines for our projects. This should be unified and defined, so that source could does not jump around in each commit (and we use more than 120 chars wide lines 😀)

**Comment by Nicolas-Boltz** [comment]
Add a maven profile in the .pom that runs spotless-maven-plugin with apply. Add gh-action that only runs on a merge on main that runs maven with the profile and adds commit to main if something has been changed
