### ISSUE TITLE
FlowGraph contains Node with no Edges

### ISSUE THREAD

**Issue by uuqjz** [DataFlowAnalysis/DataFlowAnalysis#144]
When examining the CWA, I noticed multiple vertices that are not connected to anything.
These nodes are Beginning and Usage Nodes:
![Bildschirmfoto 2024-04-03 um 10 59 18](https://github.com/DataFlowAnalysis/DataFlowAnalysis/assets/131791812/60b72e93-811c-4f32-9cc9-5856db5516a1)
This is the corresponding WebJSON:
[cwa.json](https://github.com/DataFlowAnalysis/DataFlowAnalysis/files/14849640/cwa.json)

**Comment by sebinside** [comment]
This also applies to other PCM models like the Travel Planner. We don't know whether it is a modeling problem, a problem in the flow graph finder, in the internal representation, or in the converter. Subject to further investigation.

**Comment by sebinside** [comment]
@01Parzival10 will investigate whether this also happens in MaaS

**Comment by sebinside** [comment]
The CWA is available here: https://github.com/abunai-dev/CaseStudy-CoronaWarnApp/

**Comment by 01Parzival10** [comment]
This seems to be a problem with the Conversion from the TFG to the DFD model.
Analyzing TravelPlanner only creates two connected TFGs, while the resulting DFD has Nodes with no Edges
Investigating further

**Comment by uuqjz** [comment]
Can we close this now?

**Comment by Entenwilli** [comment]
Closed by https://github.com/DataFlowAnalysis/Converter/pull/2
