### ISSUE TITLE
Insufficient handling of cyclic transpose flow graphs

### ISSUE THREAD

**Issue by BenjaminArp** [DataFlowAnalysis/DataFlowAnalysis#150]
While analyzing anilallewar_0 the DFDTransposeFlowGraphFinder infinitly calls determineSinks() until a Stackoverflow is reached.
Relevant files attached (branch constraint-modeling).
[Bug.zip](https://github.com/DataFlowAnalysis/DataFlowAnalysis/files/15292980/Bug.zip)

**Comment by sebinside** [comment]
Will be addressed with #157
