### ISSUE TITLE
QoL improvements of product and updatesite

### ISSUE THREAD

**Issue by Nicolas-Boltz** [DataFlowAnalysis/DataFlowAnalysis#162]
Various smaller fixes to improve product and day-to-day use of our stuff.

- [x] No console on product startup
- [x] Increased max heap size of product
- [x] Automatic attaching of built products in release 
- [x] Deploy source features on updatesite
- [x] Include source features in product
- [x] Remove default PCM perspective

**Comment by Nicolas-Boltz** [comment]
In relation to:

- https://github.com/DataFlowAnalysis/product/pull/12
- https://github.com/DataFlowAnalysis/product/pull/13
- https://github.com/DataFlowAnalysis/product/pull/15

**Comment by Entenwilli** [comment]
The product workflow now works as well: See https://github.com/DataFlowAnalysis/product/actions/runs/9345978731

**Comment by Entenwilli** [comment]
Remove default perspective here: https://github.com/DataFlowAnalysis/product/commit/953e1739af6028c14c7832e388f243ea221ae0c5

**Comment by Nicolas-Boltz** [comment]
https://github.com/DataFlowAnalysis/product/pull/19 adds sources to product.
