### ISSUE TITLE
PCM to DFD converter should respect labels on out pins

### ISSUE THREAD

**Issue by sebinside** [DataFlowAnalysis/DataFlowAnalysis#170]
From our last meeting, the DFD generated from PCM models should not contain forwarding assignments but the result of the label propagation as set assignments.

**Comment by sebinside** [comment]
Result from a very long discussion: @01Parzival10 fixes the pin issue, @Entenwilli does some magic to generate correct assignments and thus correct DFDs

**Comment by Nicolas-Boltz** [comment]
#203 follows up on several points for refactoring the converter.
If the points of this issue are otherwise addressed, we can close it in out meeting tomorrow.

**Comment by Entenwilli** [comment]
Completed by https://github.com/DataFlowAnalysis/Converter/pull/9

**Comment by sebinside** [comment]
k![Image](https://github.com/user-attachments/assets/c31ed699-2e65-42da-aa8c-e5d136cfcb83)
