### ISSUE TITLE
Unit-Tests of converter fail to resolve nodecharacteristics in product

### ISSUE THREAD

**Issue by Nicolas-Boltz** [DataFlowAnalysis/DataFlowAnalysis#186]
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.emf.ecore.xmi.PackageNotFoundException: Package with uri 'http://dataflowanalysis.org/pcm/extension/nodecharacteristics/0.1.0' not found. (platform:/plugin/org.dataflowanalysis.examplemodels/casestudies/TravelPlanner/travelPlanner.nodecharacteristics, 2, 344)

**Comment by Entenwilli** [comment]
I cannot reproduce this issue with the latest version of the product (from 2024-Jul-15 14:32)

**Comment by Nicolas-Boltz** [comment]
Fixed by https://github.com/DataFlowAnalysis/DataFlowAnalysis/pull/188
