### ISSUE TITLE
WedEditor delimter needs change

### ISSUE THREAD

**Issue by uuqjz** [DataFlowAnalysis/DataFlowAnalysis#193]
Currently optinal flows can be forwardes as `forward data_request`
and required flows as `forward data,request`
There are two problems:
- From the delimiter alone it is not clear what the semantic is
- Somethime we want to name flows with underscores `auth_server` this would conflict with the uncerscore delimter
--> We need to change at minimum the first delimiter

**Comment by sebinside** [comment]
;
