### ISSUE TITLE
Automated creation of an eclipse product

### ISSUE THREAD

**Issue by sebinside** [DataFlowAnalysis/DataFlowAnalysis#36]
We should think about the automated creation of an eclipse product with the modeling and analysis already included, e.g., as part of the nightly build. This could also address the problem of the profiles in #35.

**Comment by Entenwilli** [comment]
This issue will be resolved in the PR https://github.com/DataFlowAnalysis/product/pull/2

**Comment by sebinside** [comment]
Also remove the p2f file from the data flow analysis afterward
