### ISSUE TITLE
Remove dependency to Indirections

### ISSUE THREAD

**Issue by sebinside** [DataFlowAnalysis/DataFlowAnalysis#42]
It should be discussed whether we should and can safely remove the dependency on [Indirections](https://sdq.kastel.kit.edu/wiki/PCM_Data_Channels) in the modeling and analysis. As far as I know, nobody currently uses them with the analysis and I always remember [this](https://xkcd.com/2347/) xkcd about dependencies 🤐

**Comment by Nicolas-Boltz** [comment]
As the dependency mainly results from the metamodel repository, I created a branch where everything regarding indirections has been removed. See [remove_indirections](https://github.com/PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Metamodel/tree/remove_indirections).

Branch builds and unit test run. 
@sebinside @Entenwilli @majuwa We should build/deploy the branch and investigate if the analysis runs with this version.
